# pb_gather-firmware.xml -- Ansible playbook to print downloaded PAN-OS firmware
#   versions across multiple NFGW hosts
#   Author: Tyson Reed, no implied warranty. Released under GPL
#   v0.1 - June 14, 2019 
#
# STEPS
# update vars.yml with valid user/password
# update hosts with list of firewall addresses
#
# EXECUTE
# ansible-playbook -i hosts pb_gather-firmware.yml
#
---
- name: Gather downloaded PAN-OS versions from all firewalls
  hosts: all
  connection: local
  gather_facts: false

  vars:
    ansible_python_interpreter: /usr/bin/python

  roles:
    - role: PaloAltoNetworks.paloaltonetworks

  tasks:
  - name: Get credentials
    include_vars: "vars.yml"
    no_log: "yes"

  - name: Connect to firewall and gather facts
    panos_facts:
      provider: "{{ fw }}"

  - name: Connect to firewall and run command
    panos_op:
      provider: "{{ fw }}"
      cmd: "request system software info"
    register: "panos"

  - name: test debug
    debug:
      var: "item"
    loop: "{{ panos | json_query(filter_query) }}"
    vars: 
      filter_query: "response.result[*]"

  - copy: 
      content: "{{ panos.stdout }}" 
      dest: "{{ ansible_net_serial }}_output.json"
