# pb_gather-firmware.xml -- Ansible playbook to print downloaded PAN-OS firmware
#   versions across multiple NFGW hosts
#   Author: Tyson Reed, no implied warranty. Released under GPL
#   v0.1 - June 14, 2019 
#
# REQUIRES
# apt install jq
#
# STEPS
# update vars.yml with valid user/password
# update hosts with list of firewall addresses
#
# EXECUTE
# ansible-playbook -i hosts pb_gather-firmware.yml
#
---
- name: Gather downloaded PAN-OS versions from all firewalls
  hosts: one
  connection: local
  gather_facts: false

  vars:
    ansible_python_interpreter: /usr/bin/python

  roles:
    - role: PaloAltoNetworks.paloaltonetworks

  tasks:
  - name: Get credentials
    include_vars: "vars.yml"
    no_log: "yes"

  - name: Connect to firewall and gather facts
    panos_facts:
      provider: "{{ fw }}"
      gather_subset: ['system']

  - name: Connect to firewall and run command
    panos_op:
      provider: "{{ fw }}"
      cmd: "request system software info"
    register: panos
    # variable 'panos' contains the json array. works fine to this point
    # display it with panos.stdout
    # need to filter to downloaded only; concatenate to csv, append to file

#   - name: debug
#     debug: 
#       var: " (panos.stdout | from_json).response | json_query('result.sw-updates.versions.entry[*]') "
# 
#   - name: test debug
#     debug:
#       var: "item"
#     loop: "{{ panos | json_query(filter_query) }}"
#     vars: 
#       filter_query: "response.result[*]"
# 
# works to copy entire json to file per ngfw serial number
  - copy: 
      content: "{{ panos.stdout }}" 
      dest: "{{ ansible_net_serial }}_output.json"

  - name: process the file
    # this gets the versions but not the hostname
    shell: cat {{ ansible_net_serial }}_output.json | jq '.response.result."sw-updates".versions.entry[] | select(.downloaded=="yes") | .version' | tr '\n' ', ' 
    register: versions

  - name: debug
    debug:
      var: versions.stdout

  - name: write to output.txt
    lineinfile:
      line: "{{ ansible_net_hostname }}, {{ ansible_net_serial }}, {{ versions.stdout }}"
      insertafter: EOF
      dest: output.txt
    delegate_to: 127.0.0.1
